import React from 'react'
import type { Metadata } from "next";

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Hero from '@/components/(pages)/hire-ai-experts/Hero';
import Benifits from '@/components/(pages)/hire-ai-experts/Benifits';
import Hiw from '@/components/(pages)/hire-ai-experts/Hiw';
import Form from '@/components/(pages)/hire-ai-experts/Form';

export const metadata: Metadata = {
    title: "Hire AI Expert | Info Tech Brains",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <>
            <Navbar />
            <main>
                <Hero />
                <Benifits />
                <Hiw />
                <Form />
            </main>
            <Footer />
        </>
    )
}

export default page