import React from 'react'
import type { Metadata } from "next";

import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Hero from '@/components/(pages)/about/Hero';
import Clients from '@/components/(pages)/about/Clients';
import Services from '@/components/(pages)/about/Services';
import Awards from '@/components/(pages)/about/Awards';

export const metadata: Metadata = {
    title: "About us | Info Tech Brains",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <>
            <Navbar />
            <main>
                <Hero />
                <Clients />
                <Services />
                <Awards />
            </main>
            <Footer />
        </>
    )
}

export default page