import React from 'react'
import type { Metadata } from "next";

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Hero from '@/components/(pages)/tech/Hero';
import Tool from '@/components/(pages)/tech/Tools';

export const metadata: Metadata = {
    title: "Tech & Tools | Info Tech Brains",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <>
            <Navbar />
            <main>
                <Hero />
                <Tool />
            </main>
            <Footer />
        </>
    )
}

export default page